module Mp4 {

  export var BOX_TYPE = {
    FileTypeBox: 'ftyp',
    MovieBox: 'moov',
    MediaDataBox: 'mdat',
    MovieHeaderBox: 'mvhd',
    TrackBox: 'trak',
    TrackHeaderBox: 'tkhd',
    TrackReferenceBox: 'tref',
    TrackReferenceTypeHintBox: 'hint',
    TrackReferenceTypeDiscribeBox: 'cdsc',
    MediaBox: 'mdia',
    MediaHeaderBox: 'mdhd',
    HandlerBox: 'hdlr',
    MediaInformationBox: 'minf',
    VideoMediaHeaderBox: 'vmhd',
    SoundMediaHeaderBox: 'smhd',
    HintMediaHeaderBox: 'hmhd',
    NullMediaHeaderBox: 'nmhd',
    DataInformationBox: 'dinf',
    DataReferenceBox: 'dref',
    DataEntryUrlBox: 'url ',
    DataEntryUrnBox: 'urn ',
    SampleTableBox: 'stbl',
    TimeToSampleBox: 'stts',
    CompositionOffsetBox: 'ctts',
    ESDBox: 'esds',
    MP4VisualSampleEntry: 'mp4v',
    MP4AudioSampleEntry: 'mp4a',
    MpegSampleEntry: 'mp4s',
    SampleDescriptionBox: 'stsd',
    SampleSizeBox: 'stsz',
    SampleToChunkBox: 'stsc',
    ChunkOffsetBox: 'stco',
    SyncSampleBox: 'stss',
    ShadowSyncSampleBox: 'stsh',
    DegradationPriorityBox: 'stdp',
    PaddingBitsBox: 'padb',
    FreeSpaceBox: 'free',
    SkipBox: 'skip',
    EditBox: 'edts',
    EditListBox: 'elst',
    CopyrightBox: 'cprt',
    MovieExtendsBox: 'mvex',
    MovieExtendsHeaderBox: 'mehd',
    TrackExtendsBox: 'trex',
    MovieFlagmentBox: 'moof',
    MovieFragmentHeaderBox: 'mfhd',
    TrackFragmentBox: 'traf',
    TrackFragmentHeaderBox: 'tfhd',
    TrackRunBox: 'trun',
    TrackFragmentRandomAccessBox: 'tfra',
    MovieFragmentRandomAccessOffsetBox: 'mfro',
    SampleDependencyTypeBox: 'sdtp',
    SampleToGroupBox: 'sbgp',
    SampleGroupDescriptionBox: 'sgpd',
    VisualRollRecoveryEntry: 'roll',
    AudioRollRecoveryEntry: 'roll',
    SampleScaleBox: 'stsl',
    SubSampleInformationBox: 'subs',
    ProgressiveDownloadInfoBox: 'pdin',
    MetaBox: 'meta',
    XMLBox: 'xml ',
    BinaryXMLBox: 'bxml',
    ItemLocationBox: 'iloc',
    PrimaryItemBox: 'pitm',
    ItemProtectionBox: 'ipro',
    ItemInfoEntry: 'infe',
    ItemInfoBox: 'iinf',
    ProtectionSchemeInfoBox: 'sinf',
    OriginalFormatBox: 'frma',
    IPMPInfoBox: 'imif',

  };

  export var DESCR_TAG = {

  };
}